export const STORIES_GET_REQUEST = 'STORIES/GET/REQUEST';
export const STORIES_GET_SUCCESS = 'STORIES/GET/SUCCESS';
export const STORIES_GET_FAILURE = 'STORIES/GET/FAILURE';

export const STORIES_FETCH_REQUEST = 'STORIES/FETCH/REQUEST';
export const STORIES_FETCH_SUCCESS = 'STORIES/FETCH/SUCCESS';
export const STORIES_FETCH_FAILURE = 'STORIES/FETCH/FAILURE';

export const STORIES_HISTORY_CLEAR = 'STORIES/HISTORY/CLEAR';
